import { HttpStatus } from '@nestjs/common';

export const STATUS_CODES = {
  VALIDATION_FAILED: HttpStatus.MISDIRECTED,
  UNAUTHORIZED: HttpStatus.UNAUTHORIZED,
  FORBIDDEN: HttpStatus.FORBIDDEN,
  NOT_FOUND: HttpStatus.NOT_FOUND,
  INTERNAL_ERROR: HttpStatus.INTERNAL_SERVER_ERROR,
  LOGIN_FAILED: HttpStatus.UNAUTHORIZED,
  USER_NOT_ACTIVE: HttpStatus.FORBIDDEN,
  RESOURCE_NOT_FOUND: HttpStatus.NOT_FOUND,
  SESSION_EXPIRED: HttpStatus.UNAUTHORIZED,
  DUPLICATE_ENTRY: HttpStatus.CONFLICT,
  SUCCESS: HttpStatus.OK,
  INVALID_TOKEN: 498,
};